local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 2.0
   publish_frequency: 2.0
   width: 10.0
   height: 10.0
   resolution: 0.01
   static_map: false
   rolling_window: true
